config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: "admin#index", as: :admin_panel
  get '/tickets/invalidate/:id', to: "tickets#invalidate_ticket", as: :invalidate_ticket
  get '/tickets/filter', to: "tickets#filter"
  get '/tickets/add/:id', to: "tickets#add_ticket", as: :ticket_add
  get '/profile/remove/:id', to: "tickets#remove_ticket", as: :ticket_remove
  resources :tickets
  root "home#index"
  get '/profile', to: "home#profile", as: :profile
  get '/home/index', to: "home#index"
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
end

app/views/admin/index.html.erb
<div class="header">
  <div class="container">
    <div class="header__content"></div>
    <%= link_to "Главная", root_path %>
    <%= link_to "Поиск", tickets_filter_path %>
    <%= link_to "Профиль", :profile %>
    <% if user_signed_in? &&  current_user.admin? %>
      <%= link_to "Админ панель", admin_panel_path %>
    <% end %>
  </div>
</div>



<div class="body">
  <div class="container">
    <h1>Админ панель</h1>
    <div class="body__content"></div>
    <div id="tickets">
      <% @tickets.each do |ticket| %>
        <%= render ticket %>
        <p>
          <strong>Актуален:</strong>
          <% if ticket.relevant %>
            Да
          <% else %>
            Нет
          <% end %>
        </p>
        <p>
          <%= link_to "Show this ticket", ticket %> |
          <%= link_to "Edit this ticket", edit_ticket_path(ticket) %> |
          <%= link_to "Change relevancy of this ticket", invalidate_ticket_path(ticket) %>
          <%= button_to "Destroy this ticket", ticket, method: :delete %>
        </p>
      <% end %>
    </div>
  </div>
</div>